// <auto-generated />
using System;
using ElbilHusvagnLadda.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElbilHusvagnLadda.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ElbilHusvagnLadda.WebApi.Models.ChargePointComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChargePointId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Vote")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChargePointId");

                    b.ToTable("ChargePointComments");
                });

            modelBuilder.Entity("ElbilHusvagnLadda.WebApi.Models.ChargingPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Address2")
                        .HasColumnType("longtext");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MapCoordinates")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("NumberOfChargePoints")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ChargingPoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address1 = "Vattenfall - M2 Center",
                            Address2 = "",
                            Capacity = 150,
                            City = "Jönköping",
                            Comments = "An unknown places are dedicated for large vehicles",
                            Country = "Sweden",
                            MapCoordinates = "57.7617016947237, 14.19194294601759",
                            NumberOfChargePoints = 12,
                            PostalCode = "553 03",
                            Title = "Vattenfall InCharge, M2 Center"
                        },
                        new
                        {
                            Id = 2,
                            Address1 = "Snickargatan",
                            Address2 = "",
                            Capacity = 350,
                            City = "Mellerud",
                            Comments = "No dedicated spots, but works in many cases.",
                            Country = "Sweden",
                            MapCoordinates = "58.7058060636534, 12.454113738931984",
                            NumberOfChargePoints = 6,
                            PostalCode = "464 30",
                            Title = "IONITY, Mellerud"
                        },
                        new
                        {
                            Id = 3,
                            Address1 = "Nyponvägen 3",
                            Address2 = "",
                            Capacity = 300,
                            City = "Ljungby",
                            Comments = "Seem to be large charge points, but not confirmed.",
                            Country = "Sweden",
                            MapCoordinates = "56.81218919027184, 13.909877973820073",
                            PostalCode = "341 32",
                            Title = "Circle K Truck"
                        },
                        new
                        {
                            Id = 4,
                            Address1 = "Norra vägen 1",
                            Address2 = "",
                            Capacity = 150,
                            City = "Karlsborg",
                            Comments = "Unknown number of charging points and placement.",
                            Country = "Sweden",
                            MapCoordinates = "58.544494784622344, 14.502399970551915",
                            PostalCode = "546 34",
                            Title = "OKQ8"
                        },
                        new
                        {
                            Id = 5,
                            Address1 = "Ulvarydsvägen 2",
                            Address2 = "",
                            Capacity = 300,
                            City = "Markaryd",
                            Comments = "",
                            Country = "Sweden",
                            MapCoordinates = "56.44481279040068, 13.60326467913148",
                            NumberOfChargePoints = 8,
                            PostalCode = "285 35",
                            Title = "Allego charging station"
                        },
                        new
                        {
                            Id = 6,
                            Address1 = "Verkstadsgatan 3B",
                            Address2 = "",
                            Capacity = 240,
                            City = "Perstorp",
                            Comments = "Toilett and coffe machine(s).",
                            Country = "Sweden",
                            MapCoordinates = "56.13384948475831, 13.388062564117424",
                            NumberOfChargePoints = 8,
                            PostalCode = "284 34",
                            Title = "Rifil E.ON"
                        },
                        new
                        {
                            Id = 7,
                            Address1 = "Stridslyckegatan 4",
                            Address2 = "",
                            Capacity = 300,
                            City = "Mjölby",
                            Comments = "",
                            Country = "Sweden",
                            MapCoordinates = "58.322298745345044, 15.092630394912435",
                            NumberOfChargePoints = 6,
                            PostalCode = "595 35",
                            Title = "Quickcharge"
                        },
                        new
                        {
                            Id = 8,
                            Address1 = "Storgatan 46",
                            Address2 = "",
                            Capacity = 360,
                            City = "Arvidsjaur",
                            Comments = "",
                            Country = "Sweden",
                            MapCoordinates = "65.58818018806531, 19.19007382489225",
                            NumberOfChargePoints = 2,
                            PostalCode = "933 33",
                            Title = "Circle K/Ingo"
                        },
                        new
                        {
                            Id = 9,
                            Address1 = "Parkgatan 1",
                            Address2 = "",
                            Capacity = 360,
                            City = "Gällivare",
                            Comments = "",
                            Country = "Sweden",
                            MapCoordinates = "67.13804586955752, 20.65923215302954",
                            NumberOfChargePoints = 4,
                            PostalCode = "982 31",
                            Title = "Circle K"
                        });
                });

            modelBuilder.Entity("ElbilHusvagnLadda.WebApi.Models.ChargePointComment", b =>
                {
                    b.HasOne("ElbilHusvagnLadda.WebApi.Models.ChargingPoint", "ChargingPoint")
                        .WithMany()
                        .HasForeignKey("ChargePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingPoint");
                });
#pragma warning restore 612, 618
        }
    }
}
